chore: 修改依对等依赖的版本，不使用 ^ 锁定版本
tengmaoqing/vite-plugin-qiankun pull request #7
Opened 2021-08-18 08:09 UTC by rxliuli

简单来说，锁定版本会导致不同版本的类型定义无法兼容，例如 vite 2.3.6 与 2.4.4，它们的 plugin api 就是不完全兼容的，导致在 vite.config.ts 中配置该插件出错

2021-08-20 02:29 UTC, rxliuli commented
作者可以合并一下么？吾辈现在在 monorepo 中维护的单独版本，如果合并发布新版本就太好了

2021-08-20 04:02 UTC, tengmaoqing commented
> 作者可以合并一下么？吾辈现在在 monorepo 中维护的单独版本，如果合并发布新版本就太好了

明天有空的时候，我检查下哈

2021-08-24 03:49 UTC, tengmaoqing requested changes
rollup可以去掉，使用vite安装的rollup即可

2021-08-24 03:55 UTC, rxliuli commented on package.json
> +    "rollup": "^2.56.2",
嗯，看起来应该将 vite 作为对等依赖，而且同样使用 > 声明版本

2021-08-24 04:43 UTC, rxliuli reviewed
> rollup 可以去掉，使用 vite 安装的 rollup 即可

另外，rollup 依赖已删除

2021-08-24 04:43 UTC, rxliuli commented on package.json
> +    "rollup": "^2.56.2",
啊，吾辈忘记已经修改了 vite 依赖，另外 rollup-plugin-typescript2 这个插件有什么用么？

2021-08-24 06:48 UTC, tengmaoqing commented on package.json
> +    "rollup": "^2.56.2",
这个是插件构建打包的时候需要的

2021-08-24 06:49 UTC, tengmaoqing approved these changes

2021-08-24 06:50 UTC, merged